# Generated by Django 4.2.4 on 2024-01-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('precio_oferta', models.IntegerField()),
                ('imagen', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('autor', models.CharField(max_length=50)),
                ('puntuacion', models.IntegerField()),
            ],
        ),
    ]
