# Generated by Django 4.2.4 on 2024-01-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
                ('precio_oferta', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='cursos_imagenes/')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('categoria', models.CharField(choices=[('Desarrollo Web', 'Desarrollo Web'), ('Diseño Gráfico', 'Diseño Gráfico'), ('Programación', 'Programación')], max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('autor', models.CharField(max_length=50)),
                ('puntuacion', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
            ],
        ),
    ]
