# Generated by Django 4.2.4 on 2024-01-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='horario',
            field=models.CharField(default='', max_length=50),
        ),
    ]
