# Generated by Django 4.2.4 on 2024-01-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='descripcion',
            field=models.CharField(max_length=250),
        ),
    ]
