# Generated by Django 4.2.4 on 2024-01-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_cursos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='categoria',
            field=models.CharField(choices=[('Desarrollo Web', 'Desarrollo Web'), ('Diseño Gráfico', 'Diseño Gráfico'), ('Programación', 'Programación')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='puntuacion',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
