# Generated by Django 4.2.4 on 2024-02-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_cursos_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='categoria',
            field=models.CharField(choices=[('Desarrollo Web', 'Desarrollo Web'), ('Diseño Gráfico', 'Diseño Gráfico'), ('Programación', 'Programación'), ('Salud', 'Salud')], max_length=50),
        ),
    ]
