# Generated by Django 4.2.4 on 2024-01-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_alter_cursos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='imagen',
            field=models.ImageField(upload_to='cursos_imagenes/'),
        ),
    ]
